baseURL = "https://teaegg.net/"
languageCode = "en-us"
title = "ğ—§ğ—˜ğ—”â€¢ğ—˜ğ—šğ—š" # collections of thoughts & brew.
theme = "PaperMod"

# Allow raw HTML in front matter
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  author = "Howard Cheung"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  math = true

  [params.homeInfoParams]
    Title = "<span id='greeting'>Hi there! ğŸ‘‹</span>"
    Content = "I'm Howard, a CS student passionate about quantum computing, AI, and the ideas that move humanity forward. I enjoy deep conversations on breakthrough tech, philosophy, and bold visions for the future."

  [[params.socialIcons]]
    name = "instagram"
    url = "https://www.instagram.com/hawadoh/"
  
  [[params.socialIcons]]
    name = "x"
    url = "https://x.com/TheTeaEgg"

  [[params.socialIcons]]
    name = "discord"
    url = "https://discord.com/users/435740757635366913"

  [[params.socialIcons]]
    name = "tidal"
    url = "https://tidal.com/@howard"

  # [[params.socialIcons]]
    # name = "spotify"
    # url = "https://open.spotify.com/user/smdweittifot1ba54g5ve5hsm?si=22a478c8d6504c9c"
  
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/hawadoh"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/howdcheung"

  [[params.socialIcons]]
    name = "cv"
    url = "/files/howardCV.pdf"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:howd.cheung@gmail.com"

[menu]
  [[menu.main]]
    identifier = "journal"
    name = "Journal"
    url = "/journal/"
    weight = 1

  [[menu.main]]
    identifier = "research"
    name = "Research"
    url = "/research/"
    weight = 1

  [[menu.main]]
    identifier = "aboutme"
    name = "About Me"
    url = "/aboutme/"
    weight = 1

  [[menu.main]]
    identifier = "urss"
    parent = "research"
    name = "URSS"
    url = "/research/urss/"
    weight = 2