baseURL = "https://teaegg.net/"
languageCode = "en-us"
title = "URSS Blog"
theme = "PaperMod"

[params]
  author = "Howard"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowPostNavLinks = true
  math = true
  googleAnalytics = ""

[params.footer]
  copyright = ""
  poweredBy = false
  customText = ""

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 1